/*
  Generated by build_media.py from the verified Wikimedia Commons picks, plus the storefront
  photo from lungyai.com. Each photo ships as WebP at several widths with a JPEG fallback;
  credits render in the footer. Dish photos are representative, not the restaurant's own
  plates: replace them with real photography whenever it is available.
*/

export interface Photo {
  base: string;
  widths: number[];
  width: number;
  height: number;
  label: string;
  alt: string;
  credit: string;
  license?: string;
  licenseUrl?: string;
  sourceUrl: string;
  position?: string;
}

export const STOREFRONT_PHOTO: Photo = {
  "base": "/images/photos/storefront",
  "widths": [
    480,
    800,
    1200
  ],
  "width": 1200,
  "height": 800,
  "label": "Storefront",
  "alt": "The Lung Yai storefront on SW 8th Street: pine slat walls, a glass door and window, and stools at the counter inside",
  "credit": "Bill Wisser",
  "sourceUrl": "https://www.billwisserphoto.com/",
  "position": "40% 50%"
};

export const PHOTOS: Record<string, Photo> = {
  "khao-soi": {
    "base": "/images/photos/khao-soi",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 1200,
    "height": 960,
    "label": "Khao soi",
    "alt": "A bowl of khao soi topped with crispy noodles, with shallots and pickled greens on the side",
    "credit": "Chainwit.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Khao_Soi_Northern_Thai_food_%E0%B8%82%E0%B9%89%E0%B8%B2%E0%B8%A7%E0%B8%8B%E0%B8%AD%E0%B8%A2_%E0%B8%9C%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%AD%E0%B8%87.jpg",
    "position": "50% 50%"
  },
  "palo-moo": {
    "base": "/images/photos/palo-moo",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 1200,
    "height": 795,
    "label": "Palo moo",
    "alt": "Pork and whole eggs braised in a dark five-spice broth",
    "credit": "Takeaway",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mu_phalo.JPG",
    "position": "50% 50%"
  },
  "khao-man-gai": {
    "base": "/images/photos/khao-man-gai",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 1200,
    "height": 1200,
    "label": "Khao man gai",
    "alt": "Sliced poached chicken over rice, with a bowl of broth and dipping sauce behind",
    "credit": "Takeaway",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2013_Khao_man_kai_Chiang_Mai.jpg",
    "position": "50% 50%"
  },
  "ho-mok-talay": {
    "base": "/images/photos/ho-mok-talay",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 1200,
    "height": 1666,
    "label": "Ho mok talay",
    "alt": "Seafood curry steamed inside a young coconut",
    "credit": "Takeaway",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ho_mok_thale.jpg",
    "position": "50% 30%"
  },
  "dumplings": {
    "base": "/images/photos/dumplings",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 1200,
    "height": 900,
    "label": "Dumplings",
    "alt": "Steamed dumplings on a plate with a small bowl of soy dipping sauce",
    "credit": "Ser Amantio di Nicolao",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kanom_jeeb_at_Rice_and_Noodles_Thai_Restaurant,_Franconia.jpg",
    "position": "50% 50%"
  },
  "som-tam": {
    "base": "/images/photos/som-tam",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 1200,
    "height": 900,
    "label": "Som tam",
    "alt": "Green papaya salad with tomato and peanuts on a patterned plate",
    "credit": "lazy fri13th",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Som_tam.jpg",
    "position": "50% 50%"
  },
  "grilled-pork": {
    "base": "/images/photos/grilled-pork",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 1200,
    "height": 900,
    "label": "Grilled pork",
    "alt": "Pork skewers cooking on a grill rack",
    "credit": "Phoebus 28",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mu_ping.jpg",
    "position": "50% 50%"
  },
  "nam-prik-ong": {
    "base": "/images/photos/nam-prik-ong",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 1200,
    "height": 1200,
    "label": "Nam prik ong",
    "alt": "A bowl of nam prik ong with raw vegetables for dipping",
    "credit": "Takeaway",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nam_phrik_ong_02.jpg",
    "position": "50% 50%"
  },
  "larb-e-sarn": {
    "base": "/images/photos/larb-e-sarn",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 1200,
    "height": 800,
    "label": "Larb e-sarn",
    "alt": "Chicken larb with herbs next to a mound of rice",
    "credit": "Sodanie Chea",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Day_224-_Chicken_Larb_(7947748382).jpg",
    "position": "50% 50%"
  },
  "pad-kee-mao": {
    "base": "/images/photos/pad-kee-mao",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 1200,
    "height": 960,
    "label": "Pad kee mao",
    "alt": "Wide rice noodles stir-fried with vegetables",
    "credit": "Takeaway",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sen_yai_phat_khi_mao.jpg",
    "position": "50% 50%"
  },
  "green-curry": {
    "base": "/images/photos/green-curry",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 1200,
    "height": 800,
    "label": "Green curry",
    "alt": "Green curry with chicken and a basil leaf in a white bowl",
    "credit": "Guilhem Vellut",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Green_Curry,_Kapunka_Panoramas,_Paris_002.jpg",
    "position": "50% 50%"
  },
  "panang-curry": {
    "base": "/images/photos/panang-curry",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 1200,
    "height": 800,
    "label": "Panang curry",
    "alt": "Panang curry with beef and basil leaves",
    "credit": "Vee Satayamas",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Panang_curry_(42943883862).jpg",
    "position": "50% 50%"
  },
  "calle-ocho-street": {
    "base": "/images/photos/calle-ocho-street",
    "widths": [
      480,
      800,
      1200
    ],
    "width": 1200,
    "height": 900,
    "label": "SW 8th Street",
    "alt": "SW 8th Street in Little Havana, with palm trees and storefronts",
    "credit": "Infrogmation",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Calle_Ocho,_Peque%C3%B1a_Habana,_Miami_Enero_2018_37.jpg",
    "position": "50% 50%"
  }
};
